feat: added task graph view

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -54,6 +54,10 @@ _arg_done_id=()
 
 _arg_edit_done=false
 
+_arg_graph_week=false
+_arg_graph_start="$(date --date "30 days ago" +%Y-%m-%d)"
+_arg_graph_end="$(date +%Y-%m-%d)"
+
 _arg_list_all=false
 _arg_list_query=""
 
@@ -75,6 +79,7 @@ function print_help() {
   printf "  %b%-6s%b  %s\n" "$GREEN" "delete" "$RESET" "Permenently delete a task."
   printf "  %b%-6s%b  %s\n" "$GREEN" "done" "$RESET" "Mark an open task as completed."
   printf "  %b%-6s%b  %s\n" "$GREEN" "edit" "$RESET" "Open the todo list in your default editor."
+  printf "  %b%-6s%b  %s\n" "$GREEN" "graph" "$RESET" "Display a graph of the active tasks every week."
   printf "  %b%-6s%b  %s\n" "$GREEN" "list" "$RESET" "List tasks in the todo list."
 }
 
@@ -118,6 +123,16 @@ function print_help_edit() {
   printf "\n%bOptions:%b\n" "$YELLOW" "$RESET"
   printf "  %b%-10s%b  %s\n" "$GREEN" "-h, --help" "$RESET" "Show this message and exit."
   printf "  %b%-10s%b  %s\n" "$GREEN" "-d, --done" "$RESET" "Open the list of completed tasks."
+}
+
+function print_help_graph() {
+  printf "%bUsage:%b %s graph [OPTIONS]\n" "$YELLOW" "$RESET" "$0"
+  printf "\n  %s\n" "Display a graph of the active tasks every week."
+  printf "\n%bOptions:%b\n" "$YELLOW" "$RESET"
+  printf "  %b%-16s%b  %s\n" "$GREEN" "-h, --help" "$RESET" "Show this message and exit."
+  printf "  %b%-16s%b  %s\n" "$GREEN" "-w, --week" "$RESET" "Bin tasks by week rather than day."
+  printf "  %b%-16s%b  %s\n" "$GREEN" "-s, --start DATE" "$RESET" "Start date for the report."
+  printf "  %b%-16s%b  %s\n" "$GREEN" "-e, --end DATE" "$RESET" "End date for the report."
 }
 
 function print_help_list() {
@@ -196,6 +211,12 @@ function parse_args() {
       _arg_command="edit"
       shift
       parse_args_edit "$@"
+      break
+      ;;
+    graph)
+      _arg_command="graph"
+      shift
+      parse_args_graph "$@"
       break
       ;;
     ls | list)
@@ -409,6 +430,67 @@ function parse_args_edit() {
       ;;
     *)
       print_help_edit
+      printf "%bGot an unexpected argument '%s'%b\n" "$RED" "$1" "$RESET"
+      exit 1
+      ;;
+    esac
+    shift
+  done
+}
+
+function parse_args_graph() {
+  while test $# -gt 0; do
+    _key="$1"
+    case "$_key" in
+    -h | --help)
+      print_help_graph
+      exit 0
+      ;;
+    -h*)
+      print_help_graph
+      exit 0
+      ;;
+    -w | --week)
+      _arg_graph_week=true
+      ;;
+    -w*)
+      _arg_graph_week=true
+      _next="${_key##-w}"
+      if test -n "$_next" -a "$_next" != "$_key"; then
+        shift
+        set -- "-w" "-${_next}" "$@"
+      fi
+      ;;
+    -s | --start)
+      if [ $# -lt 2 ]; then
+        printf "%bMissing value for the optional argument '%s'%b\n" "$YELLOW" "$_key" "$RESET"
+        exit 1
+      fi
+      _arg_graph_start="$(pdate "$2" "start")" || exit 1
+      shift
+      ;;
+    --start=*)
+      _arg_graph_start="$(pdate "${_key##--start=}" "start")" || exit 1
+      ;;
+    -s*)
+      _arg_graph_start="$(pdate "${_key##-s}" "start")" || exit 1
+      ;;
+    -e | --end)
+      if [ $# -lt 2 ]; then
+        printf "%bMissing value for the optional argument '%s'%b\n" "$YELLOW" "$_key" "$RESET"
+        exit 1
+      fi
+      _arg_graph_end="$(pdate "$2" "end")" || exit 1
+      shift
+      ;;
+    --end=*)
+      _arg_graph_end="$(pdate "${_key##--end=}" "end")" || exit 1
+      ;;
+    -e*)
+      _arg_graph_end="$(pdate "${_key##-e}" "end")" || exit 1
+      ;;
+    *)
+      print_help_graph
       printf "%bGot an unexpected argument '%s'%b\n" "$RED" "$1" "$RESET"
       exit 1
       ;;
@@ -749,6 +831,66 @@ function edit() {
   else
     "${EDITOR:-nano}" "$TODO_DIR/done.txt" 
   fi
+}
+
+function graph() {
+
+  raw_list=""
+  if [ -f "$TODO_DIR/todo.txt" ]; then
+    raw_list="$(cat "$TODO_DIR/todo.txt")"
+  fi
+
+  if [ -f "$TODO_DIR/done.txt" ]; then
+    raw_list="$raw_list\n$(cat "$TODO_DIR/done.txt")"
+  fi
+  raw_list="$(echo -e "$raw_list")"
+
+  raw_table=""
+  idx=1
+  while IFS= read -r line; do
+    raw_table="$raw_table$(parse_task "$idx" "$line")\n"
+    idx=$((idx+1))
+  done < <(printf '%s\n' "$raw_list")
+
+  table=""
+
+  c="$(date -I -d "$_arg_graph_start - 1 day")"
+  accum=0
+  max=0
+  headers="$(printf "%bDate%b,%bN%b,%bP%b,%bD%b,%bBar%b" "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET")"
+  while [ "$c" != "$_arg_graph_end" ]; do
+    c="$(date -I -d "$c + 1 day")"
+
+    closed="$(grep -c -E "^([^\;]*)\;([^\;]*)\;([^\;]*)\;$(date --date "$c" +%Y-%m-%d)\;([^\;]*)\;([^\;]*)\;([^\;]*)\;([^\;]*)\;([^\;]*)$" <(echo -e "$raw_table"))"
+    created="$(grep -c -E "^([^\;]*)\;([^\;]*)\;([^\;]*)\;([^\;]*)\;$(date --date "$c" +%Y-%m-%d)\;([^\;]*)\;([^\;]*)\;([^\;]*)\;([^\;]*)$" <(echo -e "$raw_table"))"
+    accum="$((accum+created-closed))"
+
+
+    pending="$((accum-created))"
+    if [ "$pending" -lt 0 ]; then
+      pending=0
+    fi
+
+    row="$(printf "%b%s%b;%b%s%b;%b%s%b;%b%s%b;%b%s%b%b%s%b%b%s%b" \
+            "$BOLD" "$(date --date "$c" +%Y-%m-%d)" "$RESET" \
+            "$RED" "$created" "$RESET" \
+            "$YELLOW" "$pending" "$RESET" \
+            "$GREEN" "$closed" "$RESET" \
+            "$RED" "$(printf "%${created}s" '' | sed 's/ /━/g')" "$RESET" \
+            "$YELLOW" "$(printf "%${pending}s" '' | sed 's/ /━/g')" "$RESET" \
+            "$GREEN" "$(printf "%${closed}s" '' | sed 's/ /━/g')" "$RESET" \
+          )"
+
+    total="$((created+pending+closed))"
+    if [ "$max" -lt "$total" ]; then
+      max="$total"
+    fi
+
+    table="$table$row\n"
+  done
+
+  printf "%b" "$table" | column -ts";" -R 1 -N "$headers"
+
 }
 
 function list() {
